### ISSUE TITLE
Make standalone library?

### ISSUE THREAD

**Issue by MrTomRod** [cmdcolin/graphgenomeviewer#48]
Dear @cmdcolin

Looks like a great tool, I'd like to embed it into my project!

Could you provide a standalone js that can be used approximately like below?

```js
GraphGenomeViewer(
    '/path/to/file.gfa',  // gfa file
    element,              // DOM element (or ID of element)
    800,                  // width
    800                   // height
);
```

I tried to do this myself but failed. I don't understand node well enough.

**Comment by cmdcolin** [comment]
thanks for the kind words:) I'll try to make a little example on codesandbox to show the usage

**Comment by MrTomRod** [comment]
That would be great, thanks!

**Comment by cmdcolin** [comment]
this stackblitz repo demonstrates a basic usage

https://stackblitz.com/edit/vitejs-vite-hulsmo?file=src%2Fmain.tsx

the API is a bit react-y so it benefits to install both react, react-dom, and graphgenomeviewer (this package) from npm (if that is troublesome let me know, i know there is a big learning curve to both react and build tooling sometimes)

the stackblitz uses the vite bundler but any other should work too. the code uses React to render the "GFAGraph" component to the specified dom node (the `document.getElementById('root')` find the dom node to render to and the exclamation point is just typescript assertion that this should exist and be non-null) and then it renders the App component, which in turn, renders the GFAGraph component

hope that helps

i did a bunch of miscellaneous work on the code over the weekend also so hopefully it is all working still and definitely interested in how re-usability works for you

**Comment by cmdcolin** [comment]
any luck with using the library :)?

**Comment by MrTomRod** [comment]
Yes! Took a bit of tinkering, I managed to get `npm run build` to work. The result:

```text
dist/
├── assets
│   └── index-oi2Dux0R.js  // manually renamed to index.js
├── index.html
└── MT.gfa
```

I replaced the last few instructions in `index.js` with this:

```javascript
function K4(params) {
    return Tn.jsx("div", {
        children: Tn.jsx(Z4, params)
    })
}

window.graphGenomeViewer = (params) => {
    const element = params['element']
    ts.createRoot(element).render(Tn.jsx(K4, params));
    return Tn.jsx("div", {children: Tn.jsx(Z4, params)})
}
```

The essence of `index.html`:

```html
<head>
    <script type="module" crossorigin src="/assets/index.js"></script>
</head>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        window.graphGenomeViewer({
            element: document.getElementById("root"),
            url: "MT.gfa",
            data: undefined,
            drawPaths: undefined,
            drawLabels: undefined,
            colorScheme: undefined,
            width: 500,
            height: 500,
            chunkSize: undefined,
            linkSteps: undefined,
            sequenceThickness: undefined,
            linkThickness: undefined,
            theta: undefined,
            strengthCenter: undefined,
            onFeatureClick: undefined,
        })
    })
</script>
```

Now I can use the library as I wanted! Thanks!

Here's what I've made: [dist.zip](https://github.com/user-attachments/files/15916419/dist.zip).


Is there a less ugly way?

**Comment by MrTomRod** [comment]
Aaaaah, it still doesn't work as I had hoped! I can't have multiple graphgenomeviewers on one page! ☹️

[toy.zip](https://github.com/user-attachments/files/15917001/toy.zip)

```bash
unzip toy.zip
cd toy
python -m http.server 8000
# open http://localhost:8000/assemblies.html in browser
```

Screenshot:

![image](https://github.com/cmdcolin/graphgenomeviewer/assets/40867365/5baed935-9a9a-48b1-a5b4-ee30f2475660)

Explanation: "Plot" shows the gfa as SVG, what I had before but cannot be made interactive. "Assembly graph (gfa)" is supposed to show the same gfa, but only one is ever rendered!

Do you have an idea how to solve this?

**Comment by cmdcolin** [comment]
that is odd, I can reproduce the issue with multiple not showing

I'll check into this

**Comment by cmdcolin** [comment]
I published a new version of the library v5.0.1 that should fix this. It uses React 18 for the useId hook that allows each instance to have it's own "id namespace"

**Comment by MrTomRod** [comment]
It works! Thanks a lot! Will tweak the parameters to make it look nicer next.

![image](https://github.com/cmdcolin/graphgenomeviewer/assets/40867365/e8bc99f6-9e3a-4787-b2f5-2cb27a545d21)

A little detail: when re-rendering, the code prints a lot of wtfs. 😄

![image](https://github.com/cmdcolin/graphgenomeviewer/assets/40867365/6199ebac-90d7-49ca-bf1a-41fd7a40773e)

**Comment by cmdcolin** [comment]
that's great to see! yes the parameters are a little bit interesting. the "app" version of the code (hosted at https://cmdcolin.github.io/graphgenomeviewer) let's you interactively toggle some parameters but the library does not have a settings editor built in...could be a future add on.

 also lol @ the wtfs :)),  just published 5.0.2 with them removed

**Comment by cmdcolin** [comment]
note that a slightly higher "linkSteps" parameter often straightens out circular contigs...making it like 10. it makes the links more rigid

**Comment by MrTomRod** [comment]
Perfect, thanks again!

**Comment by cmdcolin** [comment]
glad to help :) let me know if you run into any other issues
